
version: '3.9'

services:
  app:
    build: .
    container_name: eshopper
    depends_on:
      - app_db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "gunicorn eshopper.wsgi:application --bind 0.0.0.0:8000"

  app_db:
    container_name: eshopper_db
    image: "postgres:15-alpine"
    env_file:
      - ./app/.env
    environment:
      - POSTGRES_PASSWORD="${DB_PASSWORD}"